# Deep Learning with Python and PyTorch
## 2.1 Neural Networks in One Dimension
Video: What's a Neural Network (https://youtu.be/Ne92tLtJQKI)

In [1]:
import torch
import torch.nn as nn
from torch import sigmoid

In [2]:
class Net(nn.Module):
    def __init__(self, D_in, H, D_out):
        super(Net, self).__init__()
        self.linear1 = nn.Linear(D_in, H)
        self.linear2 = nn.Linear(H, D_out)
    def forward(self, x):
        x = sigmoid(self.linear1(x))
        x = sigmoid(self.linear2(x))
        return x

In [3]:
#D_in = 1, H = 2, D_out = 1
model = Net(1,2,1)

In [4]:
x = torch.tensor([0.0])
yhat = model(x)
yhat

tensor([0.6841], grad_fn=<SigmoidBackward>)

In [5]:
X = torch.tensor([[0.0], [2.0], [3.0]])
yhat = model(X)
yhat

tensor([[0.6841],
        [0.6820],
        [0.6815]], grad_fn=<SigmoidBackward>)

In [6]:
#threshold 0.5
yhat = yhat > 0.5
yhat

tensor([[True],
        [True],
        [True]])

In [7]:
#the method state dictionary has the model parameters
model.state_dict()

OrderedDict([('linear1.weight',
              tensor([[ 0.8870],
                      [-0.6383]])),
             ('linear1.bias', tensor([-0.5268, -0.3141])),
             ('linear2.weight', tensor([[0.0527, 0.1227]])),
             ('linear2.bias', tensor([0.7015]))])

***One Hidden Layer using nn.Sequential***

In [8]:
model = torch.nn.Sequential(torch.nn.Linear(1,2), torch.nn.Sigmoid(), torch.nn.Linear(2,1), torch.nn.Sigmoid())

In [9]:
#we can then apply the model to train a tensor 
yhat = model(x)

***Train the model***

In [10]:
X = torch.arange(-20, 20, 1).view(-1,1).type(torch.FloatTensor)
Y = torch.zeros(X.shape[0])
Y[(X[:, 0] > 4) & (X[:,0] < 4)] = 1.0

In [11]:
X.shape, Y.shape

(torch.Size([40, 1]), torch.Size([40]))

In [12]:
Y = Y.unsqueeze(1)
Y.shape
#https://stackoverflow.com/questions/57798033/valueerror-target-size-torch-size16-must-be-the-same-as-input-size-torch

torch.Size([40, 1])

In [13]:
def train(Y, X, model, optimizer, criterion, epochs = 1000):
    cost = []
    total = 0
    for epoch in range(epochs):
        total = 0
        for y, x in zip(Y,X):
            yhat = model(x)
            loss = criterion(yhat, y)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            #cumulative loss
            total += loss.item()
        cost.append(total)
    return cost

In [14]:
criterion = nn.BCELoss()

In [15]:
model = Net(1,2,1)

In [16]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [17]:
cost = train(Y, X, model, optimizer, criterion, epochs = 1000)

C:\ProgramData\Anaconda3\lib\site-packages\torch\autograd\__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


In [18]:
cost

[21.872478276491165,
 18.076078236103058,
 15.215107321739197,
 13.022906064987183,
 11.31272754073143,
 9.954778537154198,
 8.85842502117157,
 7.959654822945595,
 7.212602913379669,
 6.5838852524757385,
 6.048814170062542,
 5.588855184614658,
 5.189883932471275,
 4.840995877981186,
 4.533655017614365,
 4.261109039187431,
 4.017954893410206,
 3.7998243495821953,
 3.6031553596258163,
 3.4250124767422676,
 3.262965753674507,
 3.114981096237898,
 2.9793469235301018,
 2.8546141535043716,
 2.739546898752451,
 2.6330886520445347,
 2.534326683729887,
 2.442470509558916,
 2.356834899634123,
 2.2768201529979706,
 2.201898753643036,
 2.1316081285476685,
 2.0655372738838196,
 2.0033250860869884,
 1.9446480683982372,
 1.8892175741493702,
 1.8367747943848372,
 1.7870876155793667,
 1.7399468701332808,
 1.6951658390462399,
 1.652572551742196,
 1.6120127867907286,
 1.5733459759503603,
 1.5364440232515335,
 1.5011904537677765,
 1.4674781542271376,
 1.4352095127105713,
 1.4042942691594362,
 1.3746501076